//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTGirls.Content {
	
	
	public partial class userInfo {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label p1;
		
		protected System.Web.UI.WebControls.Label p2;
		
		protected System.Web.UI.WebControls.Label p3;
		
		protected System.Web.UI.WebControls.Label p4;
		
		protected System.Web.UI.WebControls.Label p5;
	}
}
